openapi: 3.0.3
info:
  title: EmporioLambda BE
  description: OpenAPI for categories management
  version: 0.1.0

servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/swexception4/OpenAPI/0.1.0/categories
- description: serverless offline
  url: http://localhost:4000/dev/categories

paths:
  /categories/{id}:
    $ref: "categoriesByID.yml"
  /categories/:
    $ref: "categories.yml"